CREATE   PROCEDURE MIS_6427_USA_SIM_SWAP_INCENTIVE    
AS    
BEGIN    
    
IF OBJECT_ID('TEMPDB..#MIS_6427') is not null    
Drop table #MIS_6427    
    
SELECT LEFT(ICCID,8) ICCIDPREFIX, RIGHT(ICCID,12)  ICCID,PMSISDN, COMPLETEDDATE,CREATEDBY      
INTO #MIS_6427    
FROM MNP_USA_ATT.DBO.MNPPORTINREQUEST       
WHERE CONVERT(VARCHAR(10),COMPLETEDDATE,120) >=CONVERT(VARCHAR(10),GETDATE()-10,120) AND ISNULL(SIMCHANGETYPE,'')='SIMCHANGE' AND STATUS=10    
AND CONVERT(VARCHAR(7),COMPLETEDDATE,120) BETWEEN '2026-01' AND '2026-03'    
    
    
ALTER TABLE #MIS_6427 ADD RESELLERID  VARCHAR(50) , OFFMGRID  VARCHAR(50) ,ACCMGRID VARCHAR(50),HOTSPOTID VARCHAR(50),retailerid  VARCHAR(50)    
,RETAILER_MSISDN VARCHAR(50),RETAILER_COMM INT    
    
    
UPDATE A SET A.RESELLERID = B.RESELLERID FROM #mis_6427 A JOIN MVNOREPORT_USA_LM..VW_TRNACTIVATION B  ON  iccid BETWEEN B.ICCID_FR AND B.ICCID_TO    
    
UPDATE A SET A.HOTSPOTID = B.HOTSPOTID ,A.ACCMGRID = B.ACCMGRID ,A.OFFMGRID = B.OFFMGRID,a.RETAILERID=b.RETAILERID FROM #mis_6427 A JOIN MVNOREPORT_USA_LM..VW_DSMRETAILER B ON  A.createdby=B.RETAILERID    
    
update a set a.retailerid=b.Createdby from  #mis_6427 a   inner join (select ICCID,Createdby,ChannelName,Updatedby from  [MVNO_USA].dbo.CBOS_ESIMRequest (nolock) where ChannelName='CPOS') b on a.iccidprefix+a.ICCID=b.ICCID where a.RETAILERID is null    
    
update a set a.retailerid=b.Updatedby from  #mis_6427 a inner join (select ICCID,Createdby,ChannelName,Updatedby from  [MVNO_USA].dbo.CBOS_ESIMRequest (nolock) where ChannelName='CPOS') b on a.iccidprefix+a.ICCID=b.ICCID where a.retailerid is null    
    
UPDATE A     
SET A.RETAILERID=B.SUBMITTEDBY     
FROM #MIS_6427 A JOIN     
mvnoreport_usa_lm..VW_MSTSIMACTIVATION_CPOS   B    
ON  A.ICCID =RIGHT(B.SIMNUMBER,12)     
where a.retailerid is null    
    
UPDATE A     
SET A.OFFMGRID=B.OFFMGRID ,A.ACCMGRID=B.ACCMGRID,A.HOTSPOTID=B.HOTSPOTID ,A.RETAILER_MSISDN=B.virtual_msisdn    
FROM #MIS_6427 A JOIN     
mvnoreport_usa_lm..VW_DSMRETAILER B    
ON  A.RETAILERID =B.RETAILERID    
    
----------------CROSS CHECK    
    
--DELETE FROM #MIS_6427 WHERE CONVERT(VARCHAR(10),COMPLETEDDATE,120)='2026-01-06'    
    
--DROP TABLE MIS_6427_SIM_SWAP_DETAIL_COMM    
    
--SELECT * INTO MIS_6427_SIM_SWAP_DETAIL_COMM FROM #MIS_6427 WHERE CONVERT(VARCHAR(10),COMPLETEDDATE,120)<='2026-01-06'    
    
--SELECT * FROM #MIS_6427 WHERE ICCID NOT IN (SELECT ICCID FROM MIS_6427_SIM_SWAP_DETAIL_COMM)    
    
----------------    
    
INSERT INTO MIS_6427_SIM_SWAP_DETAIL_COMM    
SELECT A.* FROM #MIS_6427 A    
LEFT JOIN MIS_6427_SIM_SWAP_DETAIL_COMM B ON A.ICCID=B.ICCID     
WHERE B.ICCID IS NULL    
    
UPDATE MIS_6427_SIM_SWAP_DETAIL_COMM     
SET RETAILER_COMM=10     
WHERE OFFMGRID IS NOT NULL  AND RETAILERID IS NOT NULL AND RETAILER_COMM IS NULL    
    
-------------------    
    
---CROSS CHECK    
    
--select top 20 * into  mis_6427_SIM_SWAP_INSERTION from MIS_6427_SIM_SWAP_DETAIL_COMM where OFFMGRID is not null AND CONVERT(VARCHAR(10),COMPLETEDDATE,120)<='2026-01-06'    
    
--SELECT * FROM MIS_6427_SIM_SWAP_DETAIL_COMM WHERE ICCID NOT IN (SELECT ICCID FROM mis_6427_SIM_SWAP_INSERTION) AND OFFMGRID IS NOT NULL    
    
-------------------    
    
IF OBJECT_ID('MVNOREPORT_USA_LM..mis_6427_SIM_SWAP_INSERTION') is not null    
Drop table mis_6427_SIM_SWAP_INSERTION    
    
    
SELECT A.*  into mis_6427_SIM_SWAP_INSERTION    
FROM MIS_6427_SIM_SWAP_DETAIL_COMM A    
LEFT JOIN  APPSDB.dbo. [USA_Daily_Incentive_Credit_1119155] B ON A.ICCIDPREFIX+A.ICCID=B.ICCID_SALE     
WHERE B.ICCID_sale IS NULL AND A.OFFMGRID IS NOT NULL AND A.RETAILERID IS NOT NULL and CONVERT(VARCHAR(10),a.COMPLETEDDATE,120)<>CONVERT(VARCHAR(10),getdate(),120)    
    
    
insert into APPSDB.dbo. [USA_Daily_Incentive_Credit_1119155]    
(Retailer_MSISDN, ICCID_SALE, Retailer_ID, Retailer_name,insertiondate, Credit_Amount, Credit_Remarks)    
select RETAILER_MSISDN,iccidprefix+iccid,retailerid,retailerid,getdate(),retailer_comm,'PORTIN_TM_AT_'+CONVERT(VARCHAR(10),GETDATE(),120)    
FROM mis_6427_SIM_SWAP_INSERTION    
    
    
end    
    
    
    
    USE MVNOREPORT_USA_GT
   -----------------------------------------

DROP TABLE MIS_6427_STAFF_SIM_SWAP_INCENTIVE

SELECT * INTO MIS_6427_STAFF_SIM_SWAP_INCENTIVE FROM
MVNOREPORT_USA_LM..MIS_6427_SIM_SWAP_DETAIL_COMM WHERE CONVERT(VARCHAR(10),COMPLETEDDATE,120) BETWEEN '2026-01-01' AND '2026-01-31'
AND RETAILERID IS NOT NULL AND OFFMGRID IS NOT NULL


UPDATE A     
SET A.OFFMGRID=B.OFFMGRID ,A.ACCMGRID=B.ACCMGRID,A.HOTSPOTID=B.HOTSPOTID ,A.RETAILER_MSISDN=B.virtual_msisdn    
FROM MIS_6427_STAFF_SIM_SWAP_INCENTIVE A JOIN     
mvnoreport_usa_lm..VW_DSMRETAILER B    
ON  A.RETAILERID =B.RETAILERID    

--ALTER TABLE MIS_6427_STAFF_SIM_SWAP_INCENTIVE DROP COLUMN RETAILER_COMM

ALTER TABLE MIS_6427_STAFF_SIM_SWAP_INCENTIVE ADD SR VARCHAR(100),TL VARCHAR(100),AM VARCHAR(100),RM VARCHAR(100)

ALTER TABLE MIS_6427_STAFF_SIM_SWAP_INCENTIVE ADD TOPUP VARCHAR(20)

Update MIS_6427_STAFF_SIM_SWAP_INCENTIVE set SR=b.SalesRep,
TL=b.TeamLead,AM=b.AreaManager,RM=b.RegManager
from MIS_6427_STAFF_SIM_SWAP_INCENTIVE a,Mis_1717_Staff_Master_202601 b
where a.hotspotid=b.hotspotid

UPDATE MIS_6427_STAFF_SIM_SWAP_INCENTIVE 
SET TOPUP='YES'
FROM MIS_6427_STAFF_SIM_SWAP_INCENTIVE A,[MIS_1717_BS_wrkard_master_dontdrop] B
WHERE '1'+A.pmsisdn=B.msisdn and COMPLETEDDATE<topupdate

-----------CROSS CHECK
SELECT * FROM mvno_usa.dbo.TopupBundle_Commission_detailed WHERE ICCID='331829915930'

SELECT * FROM Mis_1717_USA_FCA  WHERE ICCID='331829915930' 


SELECT * FROM MIS_1717_BS_wrkard_master_dontdrop_month_202509 WHERE ICCID='331829915930'
SELECT * FROM [MIS_1717_BS_wrkard_master_dontdrop] WHERE ICCID='331860782958'
-----------CROSS CHECK
 
UPDATE MIS_6427_STAFF_SIM_SWAP_INCENTIVE SET SR=NULL WHERE SR='NAN'
UPDATE MIS_6427_STAFF_SIM_SWAP_INCENTIVE SET TL=NULL WHERE TL='NAN'
UPDATE MIS_6427_STAFF_SIM_SWAP_INCENTIVE SET AM=NULL WHERE AM='NAN'
UPDATE MIS_6427_STAFF_SIM_SWAP_INCENTIVE SET RM=NULL WHERE RM='NAN'

------------------------------SR	


DROP TABLE mis_6427_sim_swap_SR



;WITH CTE AS (
SELECT HOTSPOTID,SR,COUNT(ICCID) cnt
FROM MIS_6427_STAFF_SIM_SWAP_INCENTIVE
WHERE TOPUP='YES' and sr is not null 
GROUP BY HOTSPOTID,SR
)
select * into mis_6427_sim_swap_SR from cte




ALTER TABLE mis_6427_sim_swap_SR add  SLAB VARCHAR(50)

UPDATE mis_6427_sim_swap_SR
SET comm= 
CASE 
WHEN cnt>=500 then (99*1)+(100*2)+(300*3)+((cnt-499)*4) 
WHEN cnt>=200 then (99*1)+(100*2)+((cnt-199)*3)
WHEN cnt>=100 then (99*1)+((cnt-99)*2)
else cnt*1
end

--WHEN cnt between 100 and 199 THEN 'SLAB2'
--WHEN cnt between 200 and 499 THEN 'SLAB3'
--ELSE 'SLAB4' END 

ALTER TABLE mis_6427_sim_swap_SR ADD COMM VARCHAR(20)

--UPDATE mis_6427_sim_swap_SR
--SET COMM= CASE WHEN SLAB='SLAB1' THEN cnt*1
--WHEN SLAB='SLAB2' THEN cnt*2
--WHEN SLAB='SLAB3' THEN cnt*3
--WHEN SLAB='SLAB4' THEN cnt*4
--END

-----------------------------TL
drop table mis_6427_sim_swap_TL


;WITH CTE AS (
SELECT tl,COUNT(ICCID) cnt
FROM MIS_6427_STAFF_SIM_SWAP_INCENTIVE
WHERE TOPUP='YES' and tl is not null 
GROUP BY tl
)
select * into mis_6427_sim_swap_TL from cte




--ALTER TABLE mis_6427_sim_swap_TL add  SLAB VARCHAR(50)

--UPDATE mis_6427_sim_swap_TL
--SET SLAB= 
--CASE 
--WHEN cnt between 0 and 99 then 'SLAB1'
--WHEN cnt between 100 and 199 THEN 'SLAB2'
--WHEN cnt between 200 and 499 THEN 'SLAB3'
--ELSE 'SLAB4' END 

ALTER TABLE mis_6427_sim_swap_TL ADD COMM VARCHAR(20)

--UPDATE mis_6427_sim_swap_TL
--SET COMM= CASE WHEN SLAB='SLAB1' THEN cnt*0.5
--WHEN SLAB='SLAB2' THEN cnt*1
--WHEN SLAB='SLAB3' THEN cnt*2
--WHEN SLAB='SLAB4' THEN cnt*3
--END

UPDATE mis_6427_sim_swap_SR
SET comm= 
CASE 
WHEN cnt>=500 then (99*0.5)+(100*1)+(300*2)+((cnt-499)*3) 
WHEN cnt>=200 then (99*0.5)+(100*1)+((cnt-199)*2)
WHEN cnt>=100 then (99*0.5)+((cnt-99)*1)
else cnt*1
end

-------------------AM

 drop table  mis_6427_sim_swap_AM

;WITH CTE AS (	
SELECT AM,COUNT(ICCID) cnt
FROM MIS_6427_STAFF_SIM_SWAP_INCENTIVE
WHERE TOPUP='YES' and AM is not null 
GROUP BY AM
)
select * into mis_6427_sim_swap_AM from cte




ALTER TABLE mis_6427_sim_swap_AM add  SLAB VARCHAR(50)

UPDATE mis_6427_sim_swap_AM
SET SLAB= 
CASE 
WHEN cnt between 0 and 99 then 'SLAB1'
WHEN cnt between 100 and 199 THEN 'SLAB2'
WHEN cnt between 200 and 499 THEN 'SLAB3'
ELSE 'SLAB4' END 

ALTER TABLE mis_6427_sim_swap_AM ADD COMM VARCHAR(20)

UPDATE mis_6427_sim_swap_AM
SET COMM= CASE WHEN SLAB='SLAB1' THEN cnt*0.5
WHEN SLAB='SLAB2' THEN cnt*1
WHEN SLAB='SLAB3' THEN cnt*1.5
WHEN SLAB='SLAB4' THEN cnt*2
END

----------RM
drop table mis_6427_sim_swap_RM

;WITH CTE AS (	
SELECT RM,COUNT(ICCID) cnt
FROM MIS_6427_STAFF_SIM_SWAP_INCENTIVE
WHERE TOPUP='YES' and RM is not null 
GROUP BY RM
)
select * into mis_6427_sim_swap_RM from cte




ALTER TABLE mis_6427_sim_swap_RM add  SLAB VARCHAR(50)

UPDATE mis_6427_sim_swap_RM
SET SLAB= 
CASE 
WHEN cnt between 0 and 99 then 'SLAB1'
WHEN cnt between 100 and 199 THEN 'SLAB2'
WHEN cnt between 200 and 499 THEN 'SLAB3'
ELSE 'SLAB4' END 

ALTER TABLE mis_6427_sim_swap_RM ADD COMM VARCHAR(20)

UPDATE mis_6427_sim_swap_RM
SET COMM= CASE WHEN SLAB='SLAB1' THEN 0
WHEN SLAB='SLAB2' THEN cnt*0
WHEN SLAB='SLAB3' THEN cnt*0.5
WHEN SLAB='SLAB4' THEN cnt*1
END

----------------------------
---backup 

select * into MIS_6427_STAFF_SIM_SWAP_INCENTIVE_202601 from MIS_6427_STAFF_SIM_SWAP_INCENTIVE


select * from MIS_6427_STAFF_SIM_SWAP_INCENTIVE_202601 where resellerid like '%hp%' and topup='yes'


select tl,case when cnt >=500  then 99   from mis_6427_sim_swap_TL 


select *  into temp from mis_6427_sim_swap_TL

alter table cnt1 int , cnt2 int,